apiVersion: rivet.adobe.com/v1
kind: Cassandra
metadata:
  name: demo-cassandra
  namespace: rivet-resources
  labels:
    environment: dev
    application: rivet-cassandra-demo
spec:
  name: cassandra_rivet_demo
  region: va6
  replicationStrategy: MULTI_REGION
  replicationFactor: 2
  replicas:
    - or2
  tables:
    - name: users
      partitionKey: user_id
      sortKey: email
      billingMode: PROVISIONED
      readCapacityUnits: 5
      writeCapacityUnits: 5
      pointInTimeRecovery: true
      tags:
        - key: Environment
          value: Dev
        - key: DeployedBy
          value: ArgoCD-GitHub
        - key: BillingMode
          value: Provisioned
    - name: sessions
      partitionKey: session_id
      billingMode: ON_DEMAND
      pointInTimeRecovery: false
      tags:
        - key: Environment
          value: Dev
        - key: DeployedBy
          value: ArgoCD-GitHub
        - key: BillingMode
          value: OnDemand
    - name: analytics
      partitionKey: user_id
      sortKey: event_timestamp
      billingMode: ON_DEMAND
      pointInTimeRecovery: true
      tags:
        - key: Environment
          value: Dev
        - key: DeployedBy
          value: ArgoCD-GitHub
        - key: BillingMode
          value: OnDemand
        - key: Purpose
          value: Analytics
  tags:
    - key: Project
      value: RivetDemo
    - key: AdobeArchPath
      value: "Identity.RVT"
    - key: CostCenter
      value: "123456"
    - key: Environment
      value: Dev
    - key: ReplicationStrategy
      value: MultiRegion
