apiVersion: rivet.adobe.com/v1
kind: Cassandra
metadata:
  name: demo-cassandra
  namespace: rivet-resources
  labels:
    environment: demo
    application: rivet-cassandra-demo
spec:
  name: cassandra_demo_from_github_argocd
  region: va6
  replicationStrategy: SINGLE_REGION
  tables:
    - name: users
      partitionKey: user_id
      sortKey: email
      billingMode: ON_DEMAND
      pointInTimeRecovery: true
      tags:
        - key: Environment
          value: Demo
        - key: DeployedBy
          value: ArgoCD-GitHub
    - name: sessions
      partitionKey: session_id
      billingMode: ON_DEMAND
      pointInTimeRecovery: false
      tags:
        - key: Environment
          value: Demo
        - key: DeployedBy
          value: ArgoCD-GitHub
  tags:
    - key: Project
      value: RivetDemo
    - key: CreatedBy
      value: ArgoCD-GitOps-GitHub
    - key: CostCenter
      value: "123456"
    - key: Environment
      value: Demo
